# Generated by Django 2.1.7 on 2019-05-24 09:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('py', 'Python'), ('dj', 'Django'), ('ui', 'UI'), ('rest', 'REST API')], max_length=100)),
                ('shifts', multiselectfield.db.fields.MultiSelectField(choices=[('mng', 'Morning'), ('aftn', 'Afternoon'), ('evng', 'Evining'), ('night', 'Night')], max_length=100)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('mng', 'Morning'), ('aftn', 'Afternoon'), ('evng', 'Evining'), ('night', 'Night')], max_length=200)),
                ('gender', models.CharField(choices=[('hyd', 'Hydrabad'), ('bang', 'Banglore'), ('che', 'Chennai'), ('pune', 'Pune')], max_length=200)),
                ('start_date', models.DateField(max_length=100)),
            ],
        ),
    ]
