# Generated by Django 2.1.7 on 2019-05-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0002_contactdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('coursr_name', models.CharField(max_length=100)),
                ('course_dur', models.IntegerField()),
                ('course_fee', models.IntegerField()),
                ('course_date', models.DateField(max_length=120)),
                ('course_time', models.TimeField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
                ('trainer_exp', models.IntegerField()),
            ],
        ),
    ]
