# Generated by Django 2.1.7 on 2019-05-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0003_coursedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedata',
            old_name='coursr_name',
            new_name='course_name',
        ),
    ]
