# Generated by Django 2.1.7 on 2019-05-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0004_auto_20190525_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedata',
            old_name='course_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='coursedata',
            old_name='course_time',
            new_name='start_time',
        ),
    ]
